#!/bin/sh
# sb-bat — battery level %
cap=$(cat /sys/class/power_supply/BAT*/capacity 2>/dev/null) || exit 0
stat=$(cat /sys/class/power_supply/BAT*/status 2>/dev/null)
case "$stat" in
    Charging)    printf "%s%%+" "$cap" ;;
    Discharging) printf "%s%%" "$cap" ;;
    Full)        printf "Full" ;;
    *)           printf "%s%%" "$cap" ;;
esac
